### ISSUE TITLE
여행지 및 플래너 좋아요 api 이슈

### ISSUE THREAD

**Issue by hoooooyeon** [taesooooo/Planner-Back#110]
여행지 좋아요 실행시
- [x] 여행지리스트 조회시, likeCount 및 likeState가 그대로 0과 false임.
- [x] 여행지 상세정보 조회시, likeState가 그대로 false임.
 
플래너 좋아요 실행시
- [x] 플래너 목록 조회시, likeState가 그대로 false임.
- [x] 플래너 조회시, likeState가 그대로 false임.

**Comment by taesooooo** [comment]
확인결과 State만 문제가 발생
